title: My AWESOME  title
author: Elizabeth Hannan
email: elizabeth@blueblaazingmedia.com
description: > # this means to ignore newlines until "baseurl:"
Wandering Aspirant Polymath +Digital Strategist +Data Science +Senior UX Designer +Adventurist, +Yogi. Healthy balanced life everyday! #Executive #Entrepreneur

# social links
twitter_username: ElizabethHannan
github_username:  /ElizabethHannan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
